const SCHEMA_SORT_ORDER = [
    'ID',
    'OwnerID',
    'Name',
    'AppName',
    'AddressName',
    'Username',
    'Active',
    'Description',
    'DefaultPriceScheduleID',
    'QuantityMultiplier',
    'IsParent',
    'ParentID',
    'AllSuppliersCanSell',
    'DefaultSupplierID',
    'ShipFromAddressID',
    'Returnable',
    'AutoForward',
    'URL',
    'SharedKey',
    'CompanyName',
    'FirstName',
    'LastName',
    'Email',
    'EventType',
    'CustomImplementationUrl',
    'HashKey',
    'ClientID',
    'DeliveryConfigID',
    'ElevatedRoles',
    'ConfigData',
    'xp',
  ]
  
  export default SCHEMA_SORT_ORDER
  