
//Basic auth configuration
const APP_NAME = import.meta.env.VITE_APP_NAME || 'Application Name'
const BASE_API_URL =
  import.meta.env.VITE_APP_ORDERCLOUD_BASE_API_URL || 'https://api.ordercloud.io/v1'
const CLIENT_ID = import.meta.env.VITE_APP_ORDERCLOUD_CLIENT_ID

// OrderCloud OpenIdConnect Configuration
const OPENID_CONNECT_ENABLED = import.meta.env.VITE_APP_ORDERCLOUD_OPENIDCONNECT_ENABLED === 'true'
const OPENID_CONNECT_CONFIG_ID = import.meta.env.VITE_APP_ORDERCLOUD_OPENIDCONNECT_CONFIG_ID || ''
const OPENIDCONNECT_ACCESS_TOKEN_QUERY_PARAM_NAME = import.meta.env.VITE_APP_ORDERCLOUD_OPENIDCONNECT_ACCESS_TOKEN_QUERY_PARAM_NAME || ''
const OPENIDCONNECT_REFRESH_TOKEN_QUERY_PARAM_NAME = import.meta.env.VITE_APP_ORDERCLOUD_OPENIDCONNECT_REFRESH_TOKEN_QUERY_PARAM_NAME || ''
const OPENIDCONNECT_IDP_ACCESS_TOKEN_QUERY_PARAM_NAME = import.meta.env.VITE_APP_ORDERCLOUD_OPENIDCONNECT_IDP_ACCESS_TOKEN_QUERY_PARAM_NAME || ''

// Site Theming
const THEME_COLOR_PRIMARY = import.meta.env.VITE_APP_PUBLIC_THEME_COLOR_PRIMARY
const THEME_COLOR_SECONDARY = import.meta.env.VITE_APP_PUBLIC_THEME_COLOR_SECONDARY
const THEME_COLOR_ACCENT = import.meta.env.VITE_APP_PUBLIC_THEME_COLOR_ACCENT
const THEME_LOGO_URL = import.meta.env.VITE_APP_PUBLIC_THEME_LOGO_URL

export {
  APP_NAME,
  BASE_API_URL,
  CLIENT_ID,
  OPENID_CONNECT_ENABLED,
  OPENID_CONNECT_CONFIG_ID,
  OPENIDCONNECT_ACCESS_TOKEN_QUERY_PARAM_NAME,
  OPENIDCONNECT_REFRESH_TOKEN_QUERY_PARAM_NAME,
  OPENIDCONNECT_IDP_ACCESS_TOKEN_QUERY_PARAM_NAME,
  THEME_COLOR_PRIMARY,
  THEME_COLOR_SECONDARY,
  THEME_COLOR_ACCENT,
  THEME_LOGO_URL,
}
